import * as R from "ramda";

import { type CompetitorRecord, SourceKind, type SourceRecord, Vertical } from "#src/registry/types.ts";

const competitorLine = (record: CompetitorRecord): string => {
  const aliases = record.aliases.length > 0 ? ` (aliases: ${record.aliases.join(", ")})` : "";
  return `| ${record.name}${aliases} | ${record.relationship} |`;
};

const sourceLine = (record: SourceRecord): string =>
  `| ${record.name} | ${record.kind} | ${record.competitor.length > 0 ? record.competitor : "—"} | ${record.url} |`;

const sectionFor = (title: string, sources: SourceRecord[]): string[] => {
  if (sources.length === 0) {
    return [];
  }
  return [
    `### ${title}`,
    "",
    "| Source | Kind | Competitor | URL |",
    "|---|---|---|---|",
    ...R.map(sourceLine, sources),
    ""
  ];
};

const KIND_ORDER: SourceKind[] = [SourceKind.Feed, SourceKind.JobBoard, SourceKind.Crawl];
const KIND_TITLES: Record<SourceKind, string> = {
  [SourceKind.Feed]: "Feeds",
  [SourceKind.JobBoard]: "Job boards",
  [SourceKind.Crawl]: "Crawl targets (Firecrawl change-tracking)"
};

const verticalSections = (vertical: Vertical, sources: SourceRecord[]): string[] => {
  const forVertical = R.filter((source: SourceRecord) => source.vertical === vertical, sources);
  if (forVertical.length === 0) {
    return [];
  }
  const byKind = R.chain(
    (kind: SourceKind) => sectionFor(KIND_TITLES[kind], R.filter((s: SourceRecord) => s.kind === kind, forVertical)),
    KIND_ORDER
  );
  return [`## Vertical: ${vertical}`, "", ...byKind];
};

const renderSourcesMarkdown = (competitors: CompetitorRecord[], sources: SourceRecord[], notes: string[]): string => {
  const header = [
    "# Aggie sources v1",
    "",
    "Seed registry for review (phase 0). Generated by `npm run registry -- --command export` —",
    "edit the seed data in `src/registry/seed.ts`, not this file.",
    "",
    "## Competitors",
    "",
    "| Competitor | Relationship |",
    "|---|---|",
    ...R.map(competitorLine, competitors),
    ""
  ];
  const sections = R.chain((vertical: Vertical) => verticalSections(vertical, sources), Object.values(Vertical));
  const notesSection = notes.length > 0 ? ["## Notes and caveats", "", ...R.map((note: string) => `- ${note}`, notes), ""] : [];
  return [...header, ...sections, ...notesSection].join("\n");
};

export { renderSourcesMarkdown };
